name: "Publish packs"
on:
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  publish_pack:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pack: ["cpp", "csharp", "go", "javascript", "python","java"]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install CodeQL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install github/gh-codeql
          gh codeql set-version 2.22.3

      - name: "Build and publish pack"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Install and publish pack
          gh codeql resolve packs
          gh codeql pack install ${{ matrix.pack }}
          gh codeql pack publish ${{ matrix.pack }}