name: "Publish packs"
on:
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  publish_pack:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pack: ["cpp", "csharp", "go", "javascript", "python","java"]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install CodeQL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install github/gh-codeql
          gh codeql set-version 2.22.3

      - name: "Build and publish pack"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Function to get compatible pack version
          function getCompatiblePack() { 
            echo -n $(curl -s https://raw.githubusercontent.com/github/codeql/codeql-cli/v$(gh codeql version --format=json | jq -r .version)/$1/ql/lib/qlpack.yml | grep version | cut -d" " -f2)
          }
          
          # Add compatible pack version for the language
          gh codeql pack add codeql/${{ matrix.pack }}-all@$(getCompatiblePack ${{ matrix.pack }}) --dir=${{ matrix.pack }}
          
          # Install and publish pack
          gh codeql resolve packs
          gh codeql pack install ${{ matrix.pack }}
          
          # Commit and push changes to qlpack.yml if modified
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ matrix.pack }}/qlpack.yml
          if ! git diff --cached --quiet; then
            git commit -m "Update qlpack.yml with compatible pack version for ${{ matrix.pack }}"
            git push
          fi
          
          gh codeql pack publish ${{ matrix.pack }}
